import type { Metadata } from "next";
import { Orbitron } from 'next/font/google';
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const orbitron = Orbitron({
weight: '400',
subsets: ['latin'],
display: 'swap'
})

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={orbitron.className}>
    <body>

    <SidebarProvider>
      <AppSidebar />
      
        <SidebarTrigger />
        {children}
      
    </SidebarProvider>
    </body>
    </html>
  )
}